#cloud-config
# Common user-data configuration
# Creates ubuntu user with password: ubuntu

users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false

# Set password using chpasswd (more reliable)
chpasswd:
  list: |\n    ubuntu:ubuntu
  expire: False

# Enable password authentication for SSH
ssh_pwauth: true

# Configure SSH
ssh:
  emit_keys_to_console: false

# Install basic packages
packages:
  - vim
  - htop
  - curl
  - wget
  - net-tools

# Set timezone
timezone: Asia/Kolkata

# Final message
final_message: "System ready! Login with ubuntu/ubuntu"
